### ISSUE TITLE
Serialize v ExceptorClient_Curl selhává

### ISSUE THREAD

**Issue by iamklob** [vlki/exceptor#1]
Při [serializaci](https://github.com/vlki/exceptor/blob/934d4d2f57d2d273839e170957c57be0c23e6c9f/client/curl/ExceptorClient/Curl.php#L69) se může stát (a příklady z praxe to dělají), že serializce vyhodí výjimku - jde o to, že se o pár řádků dřív do pole <code>$structure</code> mj. vloží i <code>$e->getTrace()</code>, záznamy v poli stacktracu obsahují i argumenty, což můžou být objekty, ty se mají serializovat... už tušíš problém?

Víc o tom [psal Fabien](http://fabien.potencier.org/article/9/php-serialization-stack-traces-and-exceptions).

**Comment by vlki** [comment]
Dobrá připomínka. Za vhodné řešení považuju ten návrh Bernharda v prvním komentáři -- nahradit objekt jménem třídy.

**Comment by iamklob** [comment]
Vyřešeno v 7b77754be362c2064ab70f9273853135b2cc5ae5

**Comment by vlki** [comment]
Ještě jsem to v 858c737dd4ab4d0e888fc3940c16742aa6435be4 upravil tak, že se předformátují jen argumenty. Chtěl bych, aby klient byl co nejtenčí. Do čitelné podoby to pak naformátuje server.
